[package]
name = "costing_sbor_decode"
version = "1.0.0"
edition = "2021"

[dependencies]
scrypto = { path = "../../../../scrypto" }
sha256 = { version = "1.5.0", default-features = false }

[lib]
crate-type = ["cdylib", "lib"]
