[package]
name = "decimal"
version = "1.0.0-rc1"
edition = "2021"

[dependencies]
scrypto = { path = "../../../../scrypto" }

[dev-dependencies]
radix-engine = { path = "../../../../radix-engine" }

[lib]
crate-type = ["cdylib", "lib"]
