[package]
name = "test_environment"
version = "1.1.1"
edition = "2021"

[dependencies]
sbor = { path = "../../../sbor" }
scrypto = { path = "../../../scrypto" }
radix-engine-common = { path = "../../../radix-engine-common" }

[dev-dependencies]
transaction = { path = "../../../transaction" }
radix-engine = { path = "../../../radix-engine" }
scrypto-unit = { path = "../../../scrypto-unit" }

[lib]
doctest = false
crate-type = ["cdylib", "lib"]