[package]
name = "generic_proxy"
version = "1.0.0"
edition = "2021"
resolver = "2"

[dependencies]
sbor = { path = "../../../../../sbor" }
scrypto = { path = "../../../../../scrypto" }

[dev-dependencies]
radix-engine = { path = "../../../../../radix-engine" }

[features]
default = []
test = []

[lib]
doctest = false
crate-type = ["cdylib", "lib"]
