[package]
name = "oracle_v1"
version = "1.0.0"
edition = "2021"

[dependencies]
scrypto = { path = "../../../../../scrypto" }

[dev-dependencies]
radix-engine = { path = "../../../../../radix-engine" }

[features]
default = []
test = []

[lib]
crate-type = ["cdylib", "lib"]
