[package]
name = "radix-substate-store-queries"
version = "1.3.0"
edition = "2021"
description = "A library for interpreting raw substates with knowledge of higher layers, from the Radix DLT project."
readme = "README.md"
license-file = "../LICENSE"
repository = "https://github.com/radixdlt/radixdlt-scrypto"

[dependencies]
sbor = { workspace = true }
radix-engine = { workspace = true }
radix-substate-store-interface = { workspace = true }
radix-common = { workspace = true }
radix-engine-interface = { workspace = true }
radix-transactions = { workspace = true }
radix-rust = { workspace = true }
itertools = { workspace = true }
hex = { workspace = true }
paste = { workspace = true }

[features]
# You should enable either `std` or `alloc`
default = ["std", "moka"]
std = ["radix-engine/std", "hex/std", "sbor/std", "radix-transactions/std", "radix-engine-interface/std", "radix-common/std", "radix-substate-store-interface/std", "radix-rust/std"]
alloc = ["radix-engine/alloc", "hex/alloc", "sbor/alloc", "radix-transactions/alloc", "radix-engine-interface/alloc", "radix-common/alloc", "radix-substate-store-interface/alloc", "radix-rust/alloc"]

moka = ["radix-engine/moka"]
lru = ["radix-engine/lru"]

# Ref: https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false
