[package]
name = "system_wasm_buffers"
version = "0.1.0"
edition = "2021"

[dependencies]
scrypto = { path = "../../../../scrypto" }

[dev-dependencies]
radix-engine = { path = "../../../../radix-engine" }

[lib]
crate-type = ["cdylib", "lib"]
