[package]
name = "flash_loan"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
sbor = { version = "1.2.0-dev" }
scrypto = { version = "1.2.0-dev" }

[lib]
doctest = false
crate-type = ["cdylib", "lib"]