[package]
name = "resources-tracker-macro"
version = "1.0.0"
edition = "2021"

[lib]
doctest = false
proc-macro = true
bench = false

[dependencies]
proc-macro2 = "1.0"
syn = { git = "https://github.com/dtolnay/syn.git", tag = "1.0.93", features = ["full", "extra-traits"] }
quote = "1.0"
radix-engine-profiling = { path = "../../radix-engine-profiling" }

[features]
default = []
resource_tracker = []

