[workspace]
members = [
    "address",
    "address_reservation",
    "allocated_address",
    "arguments",
    "auth_scenarios",
    "balance_changes",
    "bucket",
    "cast",
    "component",
    "core",
    "costing",
    "clock",
    "data_validation",
    "deep_sbor",
    "consensus_manager",
    "execution_trace",
    "external_blueprint_caller",
    "fake_bucket",
    "fee",
    "fee_reserve_states",
    "identity",
    "kv_store",
    "large_package",
    "leaks",
    "local_component",
    "local_recursion",
    "metadata_component",
    "metadata2",
    "metadata3",
    "module",
    "non_fungible",
    "package",
    "package_invalid",
    "package_schema",
    "package_token",
    "proof",
    "proof_creation",
    "publish_package",
    "recall",
    "recursion",
    "reentrancy",
    "reference",
    "remote_generic_args",
    "resource",
    "role_assignment",
    "role-assignment-edge-cases",
    "static_dependencies",
    "static_dependencies2",
    "storage",
    "stored_external_component",
    "stored_resource",
    "stored_values",
    "vault",
    "royalty",
    "royalty-auth",
    "scrypto_env",
    "system",
    "threading",
    "transaction_limits",
    "transaction_runtime",
    "tx_processor_access",
    "events",
    "events_invalid",
    "logger",
    "validator",
    "wasm_non_mvp",
    "royalty-edge-cases",
    "system_wasm_buffers",
    "event-replacement",
    "decimal",
    "crypto_scrypto_v1",
    "crypto_scrypto_v2",
    "oracle_proxies/oracle_proxy_with_global",
    "oracle_proxies/oracle_proxy_with_owned",
    "oracle_proxies/oracle_generic_proxy_with_global",
    "oracles/oracle_v1",
    "oracles/oracle_v2",
    "oracles/oracle_v3",
    "steal",
    "locker-factory",
    "wasm_limits",
    "costing_sha256",
    "costing_sbor_decode",
    "costing_malloc",
]
resolver = "2"

[profile.release]
opt-level = 'z'        # Optimize for size.
lto = true             # Enable Link Time Optimization.
codegen-units = 1      # Reduce number of codegen units to increase optimizations.
panic = 'abort'        # Abort on panic.
strip = true           # Strip the symbols.
overflow-checks = true # Panic in the case of an overflow.
