[package]
name = "scrypto-abi"
version = "0.4.0"
edition = "2021"

[dependencies]
sbor = { path = "../sbor", default-features = false }
serde = { version = "1.0", default-features = false, optional = true }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["sbor/std", "serde?/std"]
alloc = ["sbor/alloc", "serde?/alloc"]

# Enable serde derives
serde = ["serde/derive", "sbor/serde"]