[package]
name = "genesis-helper"
version = "1.0.0-dev"
edition = "2021"

[dependencies]
sbor = { path = "../../../sbor" }
scrypto = { path = "../../../scrypto" }

[dev-dependencies]
transaction = { path = "../../../transaction" }
radix-engine = { path = "../../../radix-engine" }
scrypto-unit = { path = "../../../scrypto-unit" }
native-sdk = { path = "../../../native-sdk" }

[lib]
doctest = false
crate-type = ["cdylib", "lib"]
