[package]
name = "scrypto-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
scrypto = { version = "0.1", path = "../scrypto", default-features = false }
sbor = { version = "0.1", path = "../sbor", default-features = false }
serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false }

[features]
default = ["std"]
std = ["serde/std", "serde_json/std", "scrypto/std", "scrypto/serde_std", "sbor/std"]
alloc = ["serde/alloc", "serde_json/alloc", "scrypto/alloc", "scrypto/serde_alloc", "sbor/alloc"]