[package]
name = "sbor-tests"
version = "0.10.0"
edition = "2021"

[dependencies]
sbor = { path = "../sbor", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
bincode = { version = "2.0.0-rc.1", default-features = false, features = ["derive"] }
bencher = { version = "0.1.5" }

[[bench]]
name = "bench"
harness = false

[features]
default = ["std"]
std = ["serde/std", "serde_json/std", "bincode/std", "sbor/std", "sbor/std", "sbor/serde"]
alloc = ["serde/alloc", "serde_json/alloc", "bincode/alloc", "sbor/alloc", "sbor/alloc", "sbor/serde"]

[lib]
bench = false
